"""Hand-reviewed inventory of every public command wrapper.

Rows identify the subsystem contract suite that owns each method. Expected
SCPI bytes remain explicit in those tests; this table is not generated at
runtime and excludes no public wrapper.
"""

from __future__ import annotations

from inspect import isfunction

from gw_instek_asr.commands.common import CommonCommands
from gw_instek_asr.commands.data import DataCommands
from gw_instek_asr.commands.display import DisplayCommands
from gw_instek_asr.commands.input import InputCommands
from gw_instek_asr.commands.measure import MeasureCommands
from gw_instek_asr.commands.memory import MemoryCommands
from gw_instek_asr.commands.output import OutputCommands
from gw_instek_asr.commands.sequence import SequenceCommands
from gw_instek_asr.commands.simulate import SimulateCommands
from gw_instek_asr.commands.source import SourceCommands
from gw_instek_asr.commands.status import StatusCommands
from gw_instek_asr.commands.system import SystemCommands

INVENTORY = {
    "clear_status": "common",
    "standard_event_status_enable": "common",
    "standard_event_status": "common",
    "idn": "common",
    "identify": "common",
    "operation_complete": "common",
    "wait_for_completion": "common",
    "recall": "common",
    "reset": "common",
    "save": "common",
    "service_request_enable": "common",
    "status_byte": "common",
    "wait": "common",
    "sequence_clear": "data",
    "sequence_recall": "data",
    "sequence_store": "data",
    "simulation_clear": "data",
    "simulation_recall": "data",
    "simulation_store": "data",
    "wave_clear": "data",
    "wave_data": "data",
    "design_mode": "display",
    "measure_source": "display",
    "gain": "input",
    "sync_source": "input",
    "current_crest_factor": "measure",
    "current_high": "measure",
    "current_low": "measure",
    "current_peak_clear": "measure",
    "current_peak_hold": "measure",
    "current_rms": "measure",
    "current_average": "measure",
    "current_harmonic_rms": "measure",
    "current_harmonic_ratio": "measure",
    "measure_frequency": "measure",
    "power_apparent": "measure",
    "power_factor": "measure",
    "power_reactive": "measure",
    "power_real": "measure",
    "voltage_rms": "measure",
    "voltage_average": "measure",
    "voltage_high": "measure",
    "voltage_low": "measure",
    "voltage_harmonic_rms": "measure",
    "voltage_harmonic_ratio": "measure",
    "sensing": "measure",
    "average_count": "measure",
    "update_rate": "measure",
    "memory_recall": "memory",
    "memory_save": "memory",
    "output_state": "output",
    "output_on": "output",
    "output_off": "output",
    "power_on_state": "output",
    "protection_clear": "output",
    "output_relay": "output",
    "common_parameter": "sequence",
    "sequence_current_step": "sequence",
    "current_jump_count": "sequence",
    "sequence_current_time": "sequence",
    "step_parameter": "sequence",
    "step": "sequence",
    "sequence_condition": "sequence",
    "sequence_execute": "sequence",
    "simulation_condition": "simulate",
    "abnormal_code": "simulate",
    "abnormal_frequency": "simulate",
    "abnormal_start_phase_enable": "simulate",
    "abnormal_start_phase": "simulate",
    "abnormal_stop_phase_enable": "simulate",
    "abnormal_stop_phase": "simulate",
    "abnormal_time": "simulate",
    "abnormal_voltage": "simulate",
    "simulation_current_step": "simulate",
    "current_repeat_count": "simulate",
    "simulation_current_time": "simulate",
    "initial_code": "simulate",
    "initial_frequency": "simulate",
    "initial_start_phase_enable": "simulate",
    "initial_start_phase": "simulate",
    "initial_stop_phase_enable": "simulate",
    "initial_stop_phase": "simulate",
    "initial_voltage": "simulate",
    "normal_code": "simulate",
    "normal_frequency": "simulate",
    "normal_start_phase_enable": "simulate",
    "normal_start_phase": "simulate",
    "normal_stop_phase_enable": "simulate",
    "normal_stop_phase": "simulate",
    "normal_time": "simulate",
    "normal_voltage": "simulate",
    "repeat_count": "simulate",
    "repeat_enable": "simulate",
    "transition_time": "simulate",
    "transition_code": "simulate",
    "simulation_execute": "simulate",
    "current_limit_peak_high": "source",
    "current_limit_peak_low": "source",
    "current_limit_rms": "source",
    "current_limit_peak_mode": "source",
    "current_limit_rms_mode": "source",
    "frequency_limit_high": "source",
    "frequency_limit_low": "source",
    "frequency": "source",
    "waveform": "source",
    "thd_format": "source",
    "mode": "source",
    "start_phase_state": "source",
    "stop_phase_state": "source",
    "start_phase": "source",
    "stop_phase": "source",
    "sync_phase": "source",
    "read": "source",
    "voltage_range": "source",
    "voltage_limit_rms": "source",
    "voltage_limit_peak": "source",
    "voltage_limit_high": "source",
    "voltage_limit_low": "source",
    "voltage": "source",
    "voltage_offset": "source",
    "operation_condition": "status",
    "operation_enable": "status",
    "operation_event": "status",
    "operation_ntransition": "status",
    "operation_ptransition": "status",
    "questionable_condition": "status",
    "questionable_enable": "status",
    "questionable_event": "status",
    "questionable_ntransition": "status",
    "questionable_ptransition": "status",
    "warning_condition": "status",
    "warning_enable": "status",
    "warning_event": "status",
    "warning_ntransition": "status",
    "warning_ptransition": "status",
    "lock_condition": "status",
    "lock_enable": "status",
    "lock_event": "status",
    "lock_ntransition": "status",
    "lock_ptransition": "status",
    "preset": "status",
    "acin_detection": "system",
    "arbitrary_builtin": "system",
    "arbitrary_surge": "system",
    "arbitrary_stair": "system",
    "arbitrary_cfactor2": "system",
    "arbitrary_cfactor1": "system",
    "arbitrary_clip": "system",
    "arbitrary_store": "system",
    "arbitrary_triangle": "system",
    "arbitrary_dip": "system",
    "arbitrary_lfring": "system",
    "arbitrary_ripple": "system",
    "arbitrary_store_apply": "system",
    "beeper_state": "system",
    "gpib_address": "system",
    "lan_dhcp": "system",
    "lan_dns": "system",
    "lan_gateway": "system",
    "lan_ip": "system",
    "lan_mac": "system",
    "lan_subnet_mask": "system",
    "remote_state": "system",
    "serial_baud": "system",
    "serial_bits": "system",
    "serial_parity": "system",
    "serial_stop_bits": "system",
    "tcpip_control": "system",
    "usb_front_state": "system",
    "usb_rear_state": "system",
    "config_mode": "system",
    "extio_state": "system",
    "trigger_output_width": "system",
    "trigger_output_source": "system",
    "error": "system",
    "error_enable": "system",
    "hold_state": "system",
    "ipk_hold_time": "system",
    "key_lock": "system",
    "reboot": "system",
    "slew_mode": "system",
    "voltage_unit": "system",
    "interlock": "system",
    "slope_mode": "system",
}


def test_inventory_has_every_public_wrapper():
    mixins = (
        CommonCommands,
        DataCommands,
        DisplayCommands,
        InputCommands,
        MeasureCommands,
        MemoryCommands,
        OutputCommands,
        SequenceCommands,
        SimulateCommands,
        SourceCommands,
        StatusCommands,
        SystemCommands,
    )
    live = {
        name for mixin in mixins for name, member in mixin.__dict__.items() if not name.startswith("_") and isfunction(member)
    }
    assert set(INVENTORY) == live
    assert set(INVENTORY.values()) == {
        "common",
        "data",
        "display",
        "input",
        "measure",
        "memory",
        "output",
        "sequence",
        "simulate",
        "source",
        "status",
        "system",
    }
